
spring:
  datasource:
    url: jdbc:h2:mem:mystuff
    password: 1234
    username: root
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
server:
  port: 5050