spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: "testdb"
    password: "psw1234"
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console/
  jpa:
    hibernate:
      ddl-auto: create-drop